default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dyel_dev

test:
  <<: *default
  database: dyel_test

production:
  <<: *default
  database: dyel
